### ISSUE TITLE
Discretisation intervals

### ISSUE THREAD

**Issue by sabbatinif** [psykei/psyke-python#10]
I notice something to be fixed in the discretisation strategy. In particular, there is a problem in the assignment of boundaries to each `Interval`.

An `Interval` can be:

1. `LessThan` if ]-∞, a[
2. `GreaterThan` if ]b, +∞[
3. `Between` if [a, b]

This can be okay for discretisations into 3 bins, assuming a and b as boundaries between the bins, since both a and b belong to the middle bin.

But, what if there are 4 bins? Of course, the former is a `LessThan` and the latter is a `GreaterThan`. The two in the middle are `Between`, so they are ]-∞, a[, [a, b], [b, c], ]c, +∞[. The value equal to b is included in 2 intervals, so the intervals are overlapping. I believe that all intervals should have the form [x, y[ (with the exception of `LessThan`) or, otherwise, the form ]x, y] (with the exception of `GreaterThan`).

**Comment by MatteoMagnini** [comment]
Thanks, already solved locally, I forgot to push the changes.

**Comment by sabbatinif** [comment]
Please, check if the string representation of the different Interval subclasses is coherent with the new limits.
