### ISSUE TITLE
Discretisation strategy not as in PSyKE JVM

### ISSUE THREAD

**Issue by sabbatinif** [psykei/psyke-python#13]
I notice that the discretisation strategy does not produce the same results as in PSyKE, e.g., for the Iris data set the PetalLength attribute should be split at 2.3 and 4.9, but the actual splitting values are 3 and 4.9. Looking at the code, it seems that the supervised discretisation of PSyKE JVM has been replaced in PSyKE Python with an UNsupervised discretisation, taking into account only the value distribution for each input feature without considering the output classes.

Supervised discretisations may improve the predictive capabilities of BB classifiers. For example, by splitting the PetalWidth at 0.65 and 1.64 (as in the JVM version) it is possible to obtain a discretised feature able to separate with 100% accuracy all the Setosa Iris of the data set (since they all have PetalWidth <= 0.65). Conversely, by splitting for instance at 1 and 1.64 (as in the Python version) this does not happen, since there are some Versicolor Iris with PetalWidth < 1, as well as all the Setosa Iris.

This issue greatly impacts on the final performance of the extractors. As an example we can consider REAL applied to the Iris data set. In the JVM version it is able to explain an accurate BB predictor with 3 rules (one per class). The Python version - on average - extracts 7 rules.

**Comment by MatteoMagnini** [comment]
Yes, for the moment there is only the equi-frequence discretization strategy. This choise was made because the strategy in psyke-jvm is limited: the number of bins must be equal to the number of classes. Feel free to add any other strategies. I'll add some by myself when I can.

**Comment by gciatto-unibo** [comment]
Probably we need a naming convention and a package for discretization strategies
