### ISSUE TITLE
CART attribute error during extraction

### ISSUE THREAD

**Issue by sabbatinif** [psykei/psyke-python#2]
Error when executing the `extract` method of CART, with both classification with discretisation and regression without discretisation.

The instruction producing the exception is: `self.predictor.as_sequence()`, which should convert the tree into a sequence of leaves.

`AttributeError: 'Sequential' object has no attribute 'as_sequence'`

**Comment by MatteoMagnini** [comment]
Can you post the code when you call `extract` method? In CI there is a specific test now where both classification (with discretization and without it) and regression are covered.

**Comment by sabbatinif** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_1324/754653060.py in <module>
      1 cart = Extractor.cart(predictor, iris_features)
----> 2 theory_from_cart = cart.extract(train)
      3 print('\nCART extracted rules:\n\n' + pretty_theory(theory_from_cart))

~\Desktop\psyke\psyke-python\psyke\cart\__init__.py in extract(self, data)
     38 
     39     def extract(self, data: pd.DataFrame) -> Theory:
---> 40         return self.__create_theory(self.predictor.as_sequence(), data)
     41 
     42     def predict(self, data) -> Iterable:

AttributeError: 'KNeighborsClassifier' object has no attribute 'as_sequence'

**Comment by MatteoMagnini** [comment]
Is `predictor` a neural network? For the moment cart accepts only `DecisionTreeClassifier` and `DecisionTreeRegressor` from sklearn. Asap I'll make the algorithm accept any arbitrary predictor.

**Comment by sabbatinif** [comment]
No, actually it was a KNN.
Ok, thanks :)
